// rules for naming variables
//you cannot start with number
// example:-
// value1(valid)
// 1value(invalid)
 var value1 = "4";
 console.log(value1);
// you can use only underscore_ or $ dollar symbol

// first_name (valid)
//_firstname (valid)

//first$name(valid)
//$firstname(valid)
  var first$name = "sanju";
  console.log(first$name);
//you cannot use spaces
// first name (invalid)

// convention 
// stat with small letter and use camelCase