// trim()
// toUpperCase()
// toLowerCase()
// slice()

 let firstName = "sAnJu";
//  console.log(firstName.length);
//  firstName = firstName.trim();     // "sanju"
//  console.log(firstName);
//  console.log(firstName.length);

//  firstName = firstName.toUpperCase();
//  console.log(firstName);

//  firstName = firstName.toLowerCase();
//  console.log(firstName);

//  start index 
//  end index

//let newString = firstName.slice(0,4); // it will print 0 to 3 index
//console.log(newString);

let newString = firstName.slice(2);
console.log(newString);
// if you wil pass only one argument it will print
// rest of the string 