// typeof of opeator

// data types (primitive data type)
// string "sanju"
// number 2, 4 ,5,6
// booleans
// undefined
// null
// bigInt
// symbol

// let age = 22;
// let firstName = "sanju";

// console.log(typeof age);
// 22 --> "22"
// convert number to string
//  age = age + "";
//  console.log(typeof age);

 // convert string to number (only add +sign )
//  let myStr = "22";
//   myStr = +"22";
//   console.log(typeof myStr);

// 2nd trick
// let age = 18;
// age = String(age);
// console.log(typeof age);
let age = "18";
age = Number(age);
console.log(typeof age); 