// booleans & comparison operator 
// booleans 
// true , false 
//  let num1 = "7" ;//( this is a string data type)
//  let num2 = 7;
 //console.log(num1 == num2);// false 
 //console.log(num1 >=num2); // true 

 //== VS ===
 // console.log(num1 == num2);// false 
 //( it will not check data type it will only depends on value)
/*( if you want to check value with dataType 
 then use ===  this triple equal sign)*/

// console.log(num1 === num2);// false 

// != vs !==
let num1 = "6";
let num2 = 6;
// console.log(num1 !== num2);// true
// console.log(num1 != num2); // false 
// (!=) will check value not data type
// but ( !== ) will check value with data type 