// if else condition 
// let age = 17;
// if (age >= 18){
//     console.log("user can play ddlc");
// }else{
//     console.log("user can play mario");
// }

// let num = 14;
// if (num%2 ===0){
//     console.log("even");
// }else{
//     console.log("odd");
// }

// falsy values 

// false 
// ""
// null 
// undefined
// 0

// let firstName = 0;// "", null, 0 etc will print this kinda empty
// if (firstName){
//     console.log(firstName);
// }else{
//     console.log("firstName is kinda empty");
// }

// // truthy 
//" abc"
 // 1 , -1

 let firstName = "sanju";  // "abc", 1 to -1 are truthy
 if (firstName){
         console.log(firstName);
     }else{
        console.log("firstName is kinda empty");
    }