// if 
// else if 
// else if 
// else if 
// else 

// let tempInDegree = +prompt(" enter your wheather degree");

// if (tempInDegree < 0){
//     console.log("extremely cold outside");
// }else if (tempInDegree < 16){
//     console.log("It is cold outside ");
// }else if (tempInDegree < 25){
//     console.log("wheather is okay ");
// }else if (tempInDegree <35){
//     console.log("lets go for swim");
// }else if (tempInDegree <45){
//     console.log("turn on AC");
// }else {
//     console.log("too hot !!!");
// }
// console.log("this is next code ");

// let tempInDegree = 21;

// if(tempInDegree > 40){
//     console.log("too hot ");
// }else if (tempInDegree > 30){
//     console.log("ltes go for swim ");
// }else if (tempInDegree >20){
//     console.log("weather is cool");
// }else if (tempInDegree > 10){
//     console.log("it is very cold outside ");
// }else {
//     console.log("extremely cold outside");

// }
// console.log("hello world ");