// while loop example
 
// let num = 10;
// let i = 1;
// let sum = 0;
// while(i<=10){
    
//     sum = sum+i;
//     i++;
// }
// console.log(sum);


   // while loop 
   // sum of n number 
   let num = 100;
   
   let i = 1;
   let sum = 0;

//    while(i<=10){
//     sum = sum+i;
//     i++;
//    }
//    console.log(sum);
//    console.log(`current value of i ${i}`);

 sum = (num*(num+1))/2;
console.log(sum);   // this is fastest method 

    
