//break keyword
// continue keyword

// for(let i = 1; i<=10; i++){
//     if(i===4){
//         break;
//     }
//     console.log(i);   // 1 , 2 , 3 will print
// }

for(let i = 1; i<=10; i++){
    if(i===4){
        continue;
    }
    console.log(i);// 4 will not print 

}console.log("hello there ");

// 1
// 24.JS:15 2
// 24.JS:15 3
// 24.JS:15 5
// 24.JS:15 6
// 24.JS:15 7
// 24.JS:15 8
// 24.JS:15 9
// 24.JS:15 10
// 24.JS:17 hello there 