// intro to arrays 
// reference type 
// how to create arrays

//oredered collection of items

//  let fruits = ["apple","mango","grapes"];
//  let numbers = [1,2,3,4];
//  let mixed = [1,2,3,4, "string",null , undefined];
//  console.log(mixed);
//  console.log(numbers);
//  console.log(fruits[2]);
 let fruits = ["apple","mango", "grapes"];
 let obj = {} // object leteral
 console.log(fruits);
 fruits[1]= "banana";
 console.log(fruits);
 console.log(typeof furits);
 console.log(typeof obj);
 console.log(Array.isArray(fruits));
 console.log(Array.isArray(obj));
