// let score = 400;
// console.log(score);

// let balance = new Number(100);
// console.log(balance);
// console.log(balance.toString().length);
// console.log(Math.max(4,3,6,8));


// for loop in array 
let fruits = ["applle","mango","grapes","banana"];
console.log(fruits.length);
let fruits2 = [];
for(let i= 0; i<=fruits.length-1; i++){
    fruits2.push(fruits[i].toUpperCase());
}
console.log(fruits2);