// TRUTHY AND FALSY VALUES

// const userEmail = [];

// if(userEmail){
//     console.log("Got user email");
// }else {
//     console.log("Don't have user email");
// }

// falsy values 

// false , 0, -0, Bigint 0n, null, undefined, NaN

// truthy values 
// "0", 'false' ," ", [], {}, functio(){}

// if (userEmail.length === 0){
//     console.log("array is empty ");

// }

// const emptyObj ={};
// if(Object.keys(emptyObj).length === 0){
//     console.log("Object is empty ");
// }

// Nullish Coalescing Operator(??): null undefined 

// let val1;
// val1 = 5 ?? 10
// val1 = null?? 10 
// val1 = 10 ??15
// // val1 = undefined?? 20 
// console.log(val1);

// ternary operator 
 // condition? true :false 

 const iceTeaPrice = 99 ;
 iceTeaPrice >= 100? console.log("greater or equal"):
 console.log("less than 100");